version: "3"

services:
  notebook:
    image: "matcomuh/ml:latest"
    ports:
      - "8888:8888"
    volumes:
      - ".:/home/hlt"
      - "~/gensim-data:/root/gensim-data"
      - "~/nltk_data:/root/nltk_data"
    working_dir: "/home/hlt"
    command: "jupyter notebook --allow-root --NotebookApp.ip=0.0.0.0 --NotebookApp.token= --no-browser"

  test:
    image: "matcomuh/ml:latest"
    volumes:
      - ".:/home/hlt"
      - "~/gensim-data:/root/gensim-data"
      - "~/nltk_data:/root/nltk_data"
    working_dir: "/home/hlt"
    command: "pytest"

  example:
    image: "matcomuh/ml:latest"
    volumes:
      - ".:/home/hlt"
      - "~/gensim-data:/root/gensim-data"
      - "~/nltk_data:/root/nltk_data"
    working_dir: "/home/hlt"
    command: "python -m hltopt.examples.sklearn_opinion_ge"
