version: "3"

services:
  notebook:
    image: "matcomuh/ml:cpu"
    ports:
      - "8888:8888"
    volumes:
      - ".:/home/hpopt"
      - "~/gensim-data:/root/gensim-data"
      - "~/nltk_data:/root/nltk_data"
    working_dir: "/home/hpopt"
    command: "jupyter notebook --allow-root --NotebookApp.ip=0.0.0.0 --NotebookApp.token= --no-browser"

  test:
    image: "matcomuh/ml:cpu"
    volumes:
      - ".:/home/hpopt"
      - "~/gensim-data:/root/gensim-data"
      - "~/nltk_data:/root/nltk_data"
    working_dir: "/home/hpopt"
    command: "pytest"

  terminal:
    image: "matcomuh/ml:cpu"
    volumes:
      - ".:/home/hpopt"
      - "~/gensim-data:/root/gensim-data"
      - "~/nltk_data:/root/nltk_data"
    working_dir: "/home/hpopt"
    command: "bash"
